# Generated by Django 4.2.3 on 2023-08-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200, null=True, verbose_name='domain')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='user')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='password')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['pub_date'],
            },
        ),
    ]
